changelog:
  exclude:
    labels: ["skip-changelog"]
    authors: ["dependabot", "dependabot[bot]"]
  categories:
    - title: Breaking Changes
      labels: ["breaking"]
    - title: Features
      labels: ["type/feature"]
    - title: Bug Fixes
      labels: ["type/bug"]
    - title: Documentation
      labels: ["type/docs"]
    - title: Maintenance
      labels: ["*"]
